my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: gfiinformatiquepartner.west-europe.azure


      # User/password auth
      user: ABARET
      password: ABARET

      role: ACCOUNTADMIN
      database: ANTOINE_DB
      warehouse: WH_TALEND
      schema: DBT_ANTOINEB75
      threads: 1
      client_session_keep_alive: False
      query_tag: dbt

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)